version: 2
updates:
- package-ecosystem: docker
  directory: "/mkdocs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/mkdocs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
